name: Run Unit Tests
on:
  push:
    branches: [ main ]

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🚀 Run Unit Tests
        shell: bash
        run: |
          cd laboratories/cicd-documentation
          python3 -m unittest test_tree.py
